### ISSUE TITLE
NoMethodError while reading csv

### ISSUE THREAD

**Issue by tasin-megamind** [roo-rb/roo#376]
When I am trying to read a csv file with roo(2.7.1) and ruby(2.3.1) it gives the below exception

`rake aborted!
NoMethodError: undefined method `this' for #<Gem::Specification:0x11e782c roo-2.7.1>
/home/xxx/.rvm/gems/ruby-2.3.1/gems/roo-2.7.1/lib/roo.rb:1:in `<top (required)>'
/home/xxx/ruby_all/test-framework/config/config.rb:4:in `<top (required)>'
/home/xxx/ruby_all/test-framework/rakefile.rb:1:in `<top (required)>'
/home/xxx/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/xxx/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/xxx/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
LoadError: cannot load such file -- roo
/home/xxx/ruby_all/test-framework/config/config.rb:4:in `<top (required)>'
/home/xxx/ruby_all/test-framework/rakefile.rb:1:in `<top (required)>'
/home/xxx/.rvm/gems/ruby-2.3.1/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/xxx/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/xxx/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)`

but the older version is working well with ruby 1.9.3

**Comment by stevendaniels** [comment]
Based on this  stacktrace, I have no ability to see or understand what might be going on here.

Could you create a gist with an example file that isolates the issue? Thanks.
